### ISSUE TITLE
Details header is partly transparant

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#149]
Using Chrome browser Version 80.0.3987.132 (Official Build) (64-bit)

Would probably be nicer to make the background of the 'Score, Domain, <Standard names>' header white instead of transparant.
![image](https://user-images.githubusercontent.com/28256969/75918502-2476f780-5e5c-11ea-8b54-935c6956e7d8.png)

**Comment by stitch** [comment]
Ah, chrome. Yes. That has been pure pain, as they do something weird in their background implementation. Will give it another attempt.

**Comment by stitch** [comment]
The issue was: chrome does not set the background of a cell correctly. It overwrites the test of the next column, although it should not. This caused the rotated labels to be partially visible (when the overlap of the next cell started). There was no fixing that with z-index, layers or whatever. The only option was to set the headers as a fixed width and then let them float.

The combo of: transform: rotate(315deg); position: sticky and background color causes the issue in chrome.

The fix is far from ideal. But it works in both firefox and chrome.
