### ISSUE TITLE
Re-test individual results

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#202]
Sometimes an error occurs while performing TLS-tests (category status = "error"). These errors are mainly connectivity/communication issues between the tool and the server under test and could be attributed to either party (e.g., a mailserver ratelimits the tool while testing for STARTTLS support).
When you later re-test these domains, it is possible that the test succeeds.

It is also possible that you test a domain, it fails on certain tests, you inform the administrator and he quickly fixes the standard. In that case, a re-test of the individual result would be preferred over a re-test of the whole domain list.

**Desired solution:**
- As a dashboard user, I would like to be able to re-test individual domains within a report.
- The new results should overwrite the old results within the report. Stats should be updated accordingly.
- The report should visually indicate that a domain has been retested. Preferably the retest timestamp is logged.
- The retest option should be available for a limited timeframe, e.g. 7 days, to decrease the risk of other results becoming outdated thus making the report inacurate.
- It should be possible to re-test a domain multiple times within the allowed timeframe. The latest retest timestamp is logged.

**Comment by stitch** [comment]
Thanks for these clear user stories, this helps a lot.

Here are my first thoughts on how to approach this. The biggest concern is that complexity increases too much, which makes the tool hard to use and to maintain. Several approaches are possible, and in order to estimate the amount of time needed, i'll let this sink in for a moment.

Here are some approaches:

1: Currently reports are 'a moment in time'. This moment can be moved up a little, taking into account new scan results. The question is: how do we know what needs to be re-scanned and what not? How should this extra scan take place?

2: Perhaps it's possible to add a 'new report' based on things that are already in the database. So the same domains, but with newer things in the database.

3: Perhaps we could look up additional results that are newer (within those x days), and move the report up to that date.

4: some kind of 'patch' mechanism has to be created that breaks out of this 'moment in time' concept. A new specific scan can patch out a previous one. This can lead up to patches on patches on patches. And that has some complexity drawbacks.

5: performing a scan again, overwriting the results of an earlier scan (have to figure out what scan exactly), and somehow store that this was a re-scan.

...

Each come with their own advantages and drawbacks. The challenge is to make it work in a simple and consistent way, where a report that is being rebuilt still contains the same information.

**Comment by robinbzk** [comment]
Some ideas:

- Automatically re-test domains where one or more category status = "error". Perhaps make this an option when running a scan:
![image](https://user-images.githubusercontent.com/28256969/90529884-801c0f80-e174-11ea-97b1-d6cda247fdcd.png)

- Re-scan options menu
![image](https://user-images.githubusercontent.com/28256969/90535259-00de0a00-e17b-11ea-8ecc-698a802efc20.png)
![image](https://user-images.githubusercontent.com/28256969/90535160-e146e180-e17a-11ea-847a-ea3ceeab64ed.png)

- Perhaps an easier alternative would be the option of being able to manually edit database entries.
This would require a new view, where you get a dropdown selection list with valid attribute values per domain.
It would be like editing an Excel view of a report.
Since I think the processing of the statistics is done client side (right?), the diagrams are updated 'automatically' when refreshing the report in the browser.
For transparency purposes, a mandatory "explanation text field" should be required to explain the manual changes. These explanations could be used to fill a "Transparency pane" that could be displayed at the bottom of a report (only when manual changes were made).
![image](https://user-images.githubusercontent.com/28256969/90539886-b9f31300-e180-11ea-9fc3-a977d2187fc3.png)
