### ISSUE TITLE
Domain is missing from shared URL

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#338]
Only the path/folder is shown, the domain of the application is missing. So when you copy the link, its incomplete and unusable.

![image](https://user-images.githubusercontent.com/28256969/142668078-b027e818-f412-457c-b71c-d566a0dba28a.png)

**Comment by stitch** [comment]
Added. Happens when baseurl is empty, which is fine for most scenario's but in the case you need a complete link it's falling short. The current host of the site has now been added.

![image](https://github.com/internetstandards/Internet.nl-dashboard/assets/333846/757f1ec8-b1db-45ac-9c1a-85a911955ba1)
