### ISSUE TITLE
Report shows 100% DANE TLSA while no tlsa-records are set

### ISSUE THREAD

**Issue by mennononhebel** [internetstandards/Internet.nl-dashboard#40]
Overall web-test report shows 100% stats for DANE tlsa-records while all detail reports show correctly that no tlsa-records are set.

**Comment by stitch** [comment]
This is currently by design. The reasoning is that currently no "info" or "warning" levels are shown in the graphs. We only show things that "subtract" scores, and as info and warning don't do that, some values are always 100%. An issue about this (#18) has been created to address this. Please respond to this issue with your suggestions.

![image](https://user-images.githubusercontent.com/333846/62058851-67b41c80-b222-11e9-9d9e-f8747fa7e3f2.png)
