### ISSUE TITLE
Optimization possibilities for dashboard report data

### ISSUE THREAD

**Issue by stitch** [internetstandards/Internet.nl-dashboard#430]
Part of #425 

optimization options:
- last_scan": "2023-05-01T00:16:37.218929+00:00" can be removed, it is not shown, a lot of data
- since: can become a unix timestamp, which is an integer, so a lot shorter than a string
- compression of responses can be enabled (was disabled for some reason)

What is the maximum size of json data? Can we support 100.000 domains and do pagination per 10.000 domains for example?

**Comment by stitch** [comment]
In dev: removed the last scan field, changed the datetime format. Changed the rendering of the report table to handle 1000 domains near instantly. 5000 takes a little while but is much faster now. Can still be improved a bit.

**Comment by bwbroersma** [comment]
For compression see issue #414.
There seems to be [no browser limit](https://stackoverflow.com/questions/8937516/maximum-json-size-for-response-to-the-browser), but it will use CPU/RAM, maybe we should define and test some limits we find acceptable.
@stitch: Your conclusions the dates are very heavy on this is correct:
```bash
$ curl -sSfA '' 'https://dashboard.internet.nl/data/report/shared/websiteregister_rijksoverheid_web_jan_23/' -o '/tmp/report-sample.json' 

$ jq -c '.calculation.urls|=map(.endpoints|=map(.ratings_by_type|=map(.last_scan|=empty)))' /tmp/report-sample.json > /tmp/report-sample_without_last_scan.json

$ jq -c '.calculation.urls|=map(.endpoints|=map(.ratings_by_type|=map(.since|=("\(.[0:19])Z"|fromdateiso8601))))' /tmp/report-sample_without_last_scan.json > /tmp/report-sample_since_unixtimestamp_without_last_scan.json

$ time gzip -9kf /tmp/report-sample_*.json
gzip -9kf /tmp/report-sample_*.json  1.13s user 0.01s system 99% cpu 1.151 total

$ time brotli -7kf /tmp/report-sample_*.json 
brotli -7kf /tmp/report-sample_*.json  0.94s user 0.05s system 99% cpu 0.997 total

$ ls -l /tmp/report-sample*     
-rw-r--r-- 1 bwb bwb 25778667 May 11 19:10 /tmp/report-sample.json
-rw-r--r-- 1 bwb bwb  1902600 May 11 18:35 /tmp/report-sample.json.br
-rw-r--r-- 1 bwb bwb  1895722 May 11 18:35 /tmp/report-sample.json.gz
-rw-r--r-- 1 bwb bwb 14360156 May 11 19:11 /tmp/report-sample_since_unixtimestamp_without_last_scan.json
-rw-r--r-- 1 bwb bwb   664483 May 11 19:11 /tmp/report-sample_since_unixtimestamp_without_last_scan.json.br
-rw-r--r-- 1 bwb bwb   710617 May 11 19:11 /tmp/report-sample_since_unixtimestamp_without_last_scan.json.gz
-rw-r--r-- 1 bwb bwb 16567076 May 11 19:11 /tmp/report-sample_without_last_scan.json
-rw-r--r-- 1 bwb bwb  1157578 May 11 19:11 /tmp/report-sample_without_last_scan.json.br
-rw-r--r-- 1 bwb bwb  1163025 May 11 19:11 /tmp/report-sample_without_last_scan.json.gz
```
The major achievement is compression, a reduction of 92-95%.
Dropping `last_scan` is next with a reduction of 36-39%.
Changing `since` to a unix timestamp gives another reduction of 13% on the uncompressed data to 40% on the compressed data (since the milliseconds are also dropped in the conversion AND can't be properly compressed since they are kind of random, this saves percentage wise a lot on the compressed version).
If these 3 steps are taken the wire transfer can be reduced 97.5% when using brotli and  97.3% when using gzip.

**Comment by stitch** [comment]
What has been done in 4.2, since this was blocking usage on larger scale scale:

- [X] last scan was removed, as it was not displayed
- [X] since is a unix timestamp
- [X] compression was enabled
