### ISSUE TITLE
Security - evaluate/fix found code scanning and dependabot alerts

### ISSUE THREAD

**Issue by baknu** [internetstandards/Internet.nl-dashboard#448]

**Comment by stitch** [comment]
Updates have been implemented. The frontend repo now gets some wrong upgrade suggestions which require vue3, so they can be ignored.

**Comment by baknu** [comment]
Nice, thanks. I still see 8 Dependabot and 3 Code scanning issues. Could you solve these too?

**Comment by stitch** [comment]
Done, patched or discarded with reasoning and comments (you can see these in the security log).

One interesting issue remains which is this one. It's not possible to "just upgrade" as this upgrade might break things in unexpected and non-trivial ways. Since it requires access to the back-end i would suggest we accept the risk. If someone else has access to the back-end we have bigger and more interesting problems on our hands. At some point we should move towards this version of Celery.

https://github.com/internetstandards/Internet.nl-dashboard/security/dependabot/80

If this is an ok strategy you can close this issue or ask me to close it :)
