### ISSUE TITLE
Extend Excel conditional formatting and statistics to support > 5038 results

### ISSUE THREAD

**Issue by bwbroersma** [internetstandards/Internet.nl-dashboard#460]
Fixed in #461 demo.

**Comment by stitch** [comment]
100.000 + 13 header rows dus

**Comment by stitch** [comment]
Done. Also prepared some stuff from the #461 demo. Instead of reversing the domain there are now additional columns for suffix, domain and subdomain, which gives more flexibility.

Excel:
![image](https://github.com/internetstandards/Internet.nl-dashboard/assets/333846/84904ee9-de40-492a-8bd8-4e922002247f)

OpenDocument:
![image](https://github.com/internetstandards/Internet.nl-dashboard/assets/333846/4b3f6826-9810-4c79-814e-d82b2932c7ff)
