### ISSUE TITLE
Bug: can't add www.zinl.nl to list

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#76]
I can do a websitetest through Internet.nl:
https://www.internet.nl/site/www.zinl.nl/588678/#
https://www.internet.nl/site/www.zinl.nl/

But I can't add it to the dashboard.

**Comment by stitch** [comment]
This is due to the user interface requiring a space or comma after a domain so it changes to a box. Like this:

![image](https://user-images.githubusercontent.com/333846/66572264-f2918b80-eb70-11e9-870a-01bfa1e26237.png)

Add a space:
![image](https://user-images.githubusercontent.com/333846/66572280-f8876c80-eb70-11e9-8436-502b2a48b4ed.png)

**Comment by stitch** [comment]
Issue has been solved by moving to a simple textarea to add domains...
